import { Product } from '@/types/product.type'

export const products: Product[] = [
  {
    productId: 'P1001',
    category: 'Laptop',
    product: 'Dell XPS 13',
    unitPrice: 100000000,
    discount: 10,
    totalPrice: 1080,
    currentStock: 25,
    status: 'Active',
  },
  {
    productId: 'P1002',
    category: 'Laptop',
    product: 'MacBook Pro 14',
    unitPrice: 2000,
    discount: 5,
    totalPrice: 1900,
    currentStock: 12,
    status: 'Active',
  },
  {
    productId: 'P1003',
    category: 'Monitor',
    product: 'LG UltraWide 34”',
    unitPrice: 650,
    discount: 15,
    totalPrice: 552.5,
    currentStock: 8,
    status: 'Inactive',
  },
  {
    productId: 'P1004',
    category: 'Keyboard',
    product: 'Logitech MX Keys',
    unitPrice: 120,
    discount: 0,
    totalPrice: 120,
    currentStock: 40,
    status: 'Active',
  },
  {
    productId: 'P1005',
    category: 'Mouse',
    product: 'Razer DeathAdder V3',
    unitPrice: 75,
    discount: 20,
    totalPrice: 60,
    currentStock: 0,
    status: 'Inactive',
  },
  {
    productId: 'P1006',
    category: 'Headphones',
    product: 'Sony WH-1000XM5',
    unitPrice: 400,
    discount: 10,
    totalPrice: 360,
    currentStock: 30,
    status: 'Active',
  },
  {
    productId: 'P1007',
    category: 'Smartphone',
    product: 'iPhone 15 Pro',
    unitPrice: 1100,
    discount: 5,
    totalPrice: 1045,
    currentStock: 18,
    status: 'Active',
  },
  {
    productId: 'P1008',
    category: 'Smartphone',
    product: 'Samsung Galaxy S24',
    unitPrice: 950,
    discount: 8,
    totalPrice: 874,
    currentStock: 5,
    status: 'Inactive',
  },
  {
    productId: 'P1009',
    category: 'Tablet',
    product: 'iPad Air 11”',
    unitPrice: 800,
    discount: 10,
    totalPrice: 720,
    currentStock: 22,
    status: 'Active',
  },
  {
    productId: 'P1010',
    category: 'Printer',
    product: 'HP LaserJet Pro',
    unitPrice: 300,
    discount: 12,
    totalPrice: 264,
    currentStock: 3,
    status: 'Inactive',
  },
]
